parameters:
  - name: previewRelease
    type: boolean
    default: true
  - name: majorVersion
    type: number
    default: 0
  - name: minorVersion
    type: number
    default: 0
  - name: patchVersion
    type: number
    default: 0

trigger: none

pr:
  branches:
    include:
      - main
      
variables:
  majorVersion: ${{ parameters['majorVersion'] }}
  minorVersion: ${{ parameters['minorVersion'] }}
  patchVersion: ${{ parameters['patchVersion'] }}
  shouldPublish: $[ eq(variables['Build.Reason'], 'Manual') ]
  fullVersion: $[ format('{0}.{1}.{2}', variables['majorVersion'], variables['minorVersion'], variables['patchVersion']) ]
  ${{ if parameters['previewRelease'] }}:
    releaseVersion: $[ format('{0}-{1}.{2}', variables['fullVersion'], 'preview', variables['Build.BuildId']) ]
  ${{ else }}:
    releaseVersion: $[ format('{0}', variables['fullVersion']) ]

jobs:
  - job: Extension
    displayName: in-process and isolated NuGet packages
    steps:
      - task: UseDotNet@2
        displayName: Install .NET SDK
        inputs:
          packageType: sdk
          version: 8.x
          performMultiLevelLookup: true

      - task: DotNetCoreCLI@2
        displayName: Build Akc.Azure.WebJobs.Extensions.ActiveMQ Release
        inputs:
          command: build
          arguments: $(Build.SourcesDirectory)/src/ActiveMQBinding/ActiveMQBinding.csproj --configuration Release -property:Version=$(releaseVersion) -property:ContinuousIntegrationBuild=true

      - task: DotNetCoreCLI@2
        displayName: Build Akc.Azure.Functions.Worker.Extensions.ActiveMQ Release
        inputs:
          command: build
          arguments: $(Build.SourcesDirectory)/src/ActiveMQ.WorkerBinding/ActiveMQ.WorkerBinding.csproj --configuration Release -property:Version=$(releaseVersion) -property:ContinuousIntegrationBuild=true

      - task: DotNetCoreCLI@2
        displayName: Pack Akc.Azure.WebJobs.Extensions.ActiveMQ Release
        condition: eq(variables['shouldPublish'], 'True')
        inputs:
          command: custom
          custom: pack
          arguments: $(Build.SourcesDirectory)/src/ActiveMQBinding/ActiveMQBinding.csproj --configuration Release --no-build -property:Version=$(releaseVersion) --output $(Build.ArtifactStagingDirectory)/dotnet/$(releaseVersion)

      - task: DotNetCoreCLI@2
        displayName: Pack Akc.Azure.Functions.Worker.Extensions.ActiveMQ Release
        condition: eq(variables['shouldPublish'], 'True')
        inputs:
          command: custom
          custom: pack
          arguments: $(Build.SourcesDirectory)/src/ActiveMQ.WorkerBinding/ActiveMQ.WorkerBinding.csproj --configuration Release --no-build -property:Version=$(releaseVersion) --output $(Build.ArtifactStagingDirectory)/dotnet/$(releaseVersion)

      - task: PublishBuildArtifacts@1
        displayName: Publish Extension
        condition: eq(variables['shouldPublish'], 'True')
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'

      - task: NuGetCommand@2
        displayName: 'NuGet push packages'
        condition: eq(variables['shouldPublish'], 'True')
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: nuget.org
          packagesToPush: '$(Build.ArtifactStagingDirectory)/dotnet/$(releaseVersion)/*.nupkg'
          
