version: "3.9"

services:
    activemq:
        image: apache/activemq-artemis
        ports:
          - "61616:61616"
          - "8161:8161"
          - "5672:5672"
        environment:
            ENABLE_JMX_EXPORTER: "true"